# Generated by Django 6.1.1 on 2026-09-24 15:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(default='DEFAULT', max_length=100)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase/Purchase Order price per unit', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Actual POS billing price before discount', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('khata_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive value means customer owes money to store', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kirana & General Store', max_length=150)),
                ('tagline', models.CharField(blank=True, default='Your Trusted Neighborhood Shop', max_length=255)),
                ('address', models.TextField(default='Main Road, Market Yard, City')),
                ('phone', models.CharField(default='+91 9876543210', max_length=15)),
                ('email', models.EmailField(blank=True, default='contact@kirana.local', max_length=254)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15, null=True)),
                ('upi_id', models.CharField(default='store@upi', help_text='VPA for dynamic QR billing', max_length=100)),
                ('gst_enabled', models.BooleanField(default=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Default GST %', max_digits=5)),
                ('thermal_printer_width', models.IntegerField(default=58, help_text='58 or 80 mm')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Profile',
                'verbose_name_plural': 'Store Profile',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_invoice_id', models.CharField(db_index=True, help_text='Client side UUID for offline sync idempotency', max_length=100, unique=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR Code'), ('KHATA', 'Digital Khata (Udhaari)'), ('CARD', 'Debit/Credit Card'), ('MIXED', 'Mixed Payment')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PAID', 'Fully Paid'), ('PENDING', 'Pending Khata'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('khata_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_gst', models.BooleanField(default=True)),
                ('synced_from_offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KhataLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Udhaar Given (Credit Sales)'), ('CREDIT', 'Payment Received (Settlement)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(default='CASH', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='inventory.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khata_entries', to='inventory.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Barcode or SKU Code', max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('hsn_code', models.CharField(blank=True, default='1905', max_length=20)),
                ('unit', models.CharField(choices=[('Pcs', 'Pieces'), ('Kg', 'Kilograms'), ('Gm', 'Grams'), ('Ltr', 'Liters'), ('Ml', 'Milliliters'), ('Box', 'Box'), ('Pack', 'Pack'), ('Strip', 'Strip (Pharma)')], default='Pcs', max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST percentage e.g. 0, 5, 12, 18, 28', max_digits=5)),
                ('min_stock_alert', models.IntegerField(default=10, help_text='Reorder threshold trigger')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product'),
        ),
    ]
