# Generated by Django 6.1.1 on 2026-09-24 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeprofile',
            options={'verbose_name': 'Store Profile', 'verbose_name_plural': 'Store Profiles'},
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.storeprofile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='inventory.storeprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='inventory.storeprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.storeprofile'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_invoice_id',
            field=models.CharField(db_index=True, help_text='Client side UUID for offline sync idempotency', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Barcode or SKU Code', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'sku')},
        ),
    ]
