# Generated by Django 6.1.1 on 2026-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_storeprofile_options_category_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar Card Number', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='kyc_status',
            field=models.CharField(choices=[('VERIFIED', 'KYC Verified'), ('PENDING', 'Verification Pending'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Card Number for Merchant KYC', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='upi_id',
            field=models.CharField(default='store@upi', help_text='Store VPA for dynamic QR billing (GPay/Paytm/PhonePe)', max_length=100),
        ),
    ]
