# Generated by Django 6.1.1 on 2026-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_storeprofile_aadhaar_number_storeprofile_kyc_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='store_type',
            field=models.CharField(choices=[('PERFUME', 'Perfumes, Fragrances & Cosmetics'), ('CLOTHING', 'Apparel, Fashion & Footwear'), ('ELECTRONICS', 'Mobiles, Gadgets & Electronics'), ('GROCERY', 'Kirana, Staples & Supermarket'), ('PHARMA', 'Pharmacy & Medical Store'), ('HARDWARE', 'Hardware, Electrical & Plumbing'), ('GENERAL', 'General Retail & Gift Shop')], default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='batch',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Purchase price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='batch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Actual POS billing price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='3303', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_alert',
            field=models.IntegerField(default=5, help_text='Reorder threshold trigger'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Bottle', 'Bottle (Perfume/Liquids)'), ('Ml', 'Milliliters (Ml)'), ('Pcs', 'Pieces (Pcs)'), ('Pair', 'Pair (Footwear/Items)'), ('Set', 'Set / Combo'), ('Box', 'Box'), ('Pack', 'Pack'), ('Kg', 'Kilograms (Kg)'), ('Gm', 'Grams (Gm)'), ('Ltr', 'Liters (Ltr)'), ('Strip', 'Strip (Pharma)')], default='Pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='address',
            field=models.TextField(default='Main Road, Market Square, City'),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='email',
            field=models.EmailField(blank=True, default='contact@retail.local', max_length=254),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='name',
            field=models.CharField(default='Retail Shop & Boutique', max_length=150),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='tagline',
            field=models.CharField(blank=True, default='Your Trusted Retail Store', max_length=255),
        ),
    ]
